Repository falcosecurity/charts, pull requests merged in 2020-05, with the labels that each got.

#16 update(falco): update maintainers in Chart.yaml
  falco/Chart.yaml
Labels: approved, dco-signoff: yes, lgtm, lgtm, size/XS

#20 new: OWNERS
  OWNERS
Labels: dco-signoff: yes, size/S

#18 update(falco): chart release 1.1.8
  falco-1.1.8.tgz
  index.json
  index.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, lgtm, size/S

#21 docs: typo in README
  README.md
Labels: approved, dco-signoff: yes, lgtm, lgtm, size/XS
