Repository falcosecurity/charts, pull requests merged in 2020-07, with the labels that each got.

#39 update(falco): update Falco rules from master
  falco/rules/application_rules.yaml
  falco/rules/falco_rules.local.yaml
  falco/rules/falco_rules.yaml
  falco/rules/k8s_audit_rules.yaml
Labels: approved, dco-signoff: yes, kind/bug, kind/feature, lgtm, lgtm, size/XL

#32 Skipping any CircleCI activity on gh-pages
  .circleci/config.yml
Labels: approved, dco-signoff: yes, kind/feature, lgtm, lgtm, size/XS

#41 release(falco): 1.1.20
  falco/CHANGELOG.md
  falco/Chart.yaml
Labels: approved, dco-signoff: yes, lgtm, lgtm, size/XS

#42 fix(falco): correct wrong version number
  falco/Chart.yaml
Labels: approved, dco-signoff: yes, lgtm, lgtm, size/XS

#43 chore: cleanup unused files
  index.html
  index.json
Labels: approved, dco-signoff: yes, lgtm, lgtm, size/M

#46 build(.circleci): charts linting
  .circleci/config.yml
  .circleci/lint.sh
Labels: approved, dco-signoff: yes, lgtm, lgtm, size/S

#51 Add SCC to support Openshift
  falco/CHANGELOG.md
  falco/Chart.yaml
  falco/README.md
  falco/templates/securitycontextconstraints.yaml
  falco/values.yaml
Labels: approved, area/falco-chart, dco-signoff: yes, kind/chart-release, kind/feature, lgtm, lgtm, size/M

#52 docs(falco-exporter): correct default value for image version
  falco-exporter/README.md
Labels: approved, area/falco-exporter-chart, dco-signoff: yes, kind/documentation, lgtm, lgtm, size/XS

#56 Add 'docker.io/falcosecurity/falco' image to 'falco_privileged_images' macro
  falco/rules/falco_rules.yaml
Labels: approved, area/falco-chart, dco-signoff: yes, kind/bug, kind/chart-release, lgtm, lgtm, size/XS
