Repository falcosecurity/charts, pull requests merged in 2020-06, with the labels that each got.

#26 docs: remove dead link to old Falco profiles
  falco/README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, lgtm, size/XS

#28 docs(falco): adjust examples for helm 3
  falco/README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, lgtm, size/S

#30 fix(falco): add missing privileges for the apps Kubernetes API group
  falco/CHANGELOG.md
  falco/templates/clusterrole.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, lgtm, size/S

#34 update(falco): chart release 1.1.9
  falco-1.1.9.tgz
  index.json
  index.yaml
Labels: approved, dco-signoff: yes, lgtm, lgtm, size/M

#35 docs(falco): auditLog
  falco/README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, lgtm, size/XS
