Repository falcosecurity/charts, pull requests merged in 2021-04, with the labels that each got.

#207 GCP Storage, AWS S3, OpenFaaS, RabbitMQ all new output types values added
  falcosidekick/CHANGELOG.md
  falcosidekick/Chart.yaml
  falcosidekick/README.md
  falcosidekick/templates/secrets.yaml
  falcosidekick/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#208 falcosidekick version is upgraded on the dependencies side of Falco chart and Falco chart version is also bumped to v1.8.0
  falco/CHANGELOG.md
  falco/Chart.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#210 fix for bucket name of s3, it should be empty
  falcosidekick/CHANGELOG.md
  falcosidekick/Chart.yaml
  falcosidekick/README.md
  falcosidekick/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#211 upgraded Falcosidekick dependency to 0.3.1 for Falco, also upgraded F…
  falco/CHANGELOG.md
  falco/Chart.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#216 set default values for openfaas parameters
  falcosidekick/CHANGELOG.md
  falcosidekick/Chart.yaml
  falcosidekick/README.md
  falcosidekick/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#219 Bump up version (v1.0.1) of image for falcosidekick-ui
  falcosidekick/CHANGELOG.md
  falcosidekick/Chart.yaml
  falcosidekick/values.yaml
Labels: approved, area/falcosidekick-chart, dco-signoff: yes, kind/chart-release, lgtm, size/S

#221 [falco] update falcosidekick chart to v1.10.0
  falco/CHANGELOG.md
  falco/Chart.yaml
Labels: approved, area/falco-chart, dco-signoff: yes, kind/chart-release, lgtm, size/XS
