Repository falcosecurity/charts, pull requests merged in 2021-03, with the labels that each got.

#202 fix: update rule description
  falco/CHANGELOG.md
  falco/Chart.yaml
  falco/rules/falco_rules.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#204 Add link on GH Pages to charts' repo Readme
  index.html
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#205 build(.circleci): do not run charts job on `gh-pages` branch
  .circleci/config.yml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S
