Repository falcosecurity/charts, pull requests merged in 2023-12, with the labels that each got.

#578 Fix README link to Policy Report documentation
  charts/falcosidekick/CHANGELOG.md
  charts/falcosidekick/Chart.yaml
  charts/falcosidekick/README.md
Labels: kind/documentation, dco-signoff: yes, size/XS, approved, lgtm

#567 Update links in README
  README.md
Labels: kind/documentation, dco-signoff: yes, size/XS, approved, lgtm

#593 update(pull-request-template): add k8s-metacollector area
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dco-signoff: yes, size/XS, approved, lgtm

#594 fix(makefile): correctly updted dependencies for each chart
  Makefile
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm
