Repository falcosecurity/charts, pull requests merged in 2024-12, with the labels that each got.

#785 bump falcosidekick dependency to v0.9.* to match with future versions
  charts/falco/CHANGELOG.md
  charts/falco/Chart.yaml
  charts/falco/README.md
Labels: kind/feature, dco-signoff: yes, size/S, approved, lgtm, area/falco-chart

#786 fix value conversions errors
  charts/falcosidekick/CHANGELOG.md
  charts/falcosidekick/Chart.yaml
  charts/falcosidekick/README.md
  charts/falcosidekick/templates/secrets.yaml
  charts/falcosidekick/values.yaml
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, area/falcosidekick-chart

#789 update talon version to v0.2.1 for bug fixes
  charts/falco-talon/CHANGELOG.md
  charts/falco-talon/Chart.yaml
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm

#802 add a grafana dashboard for the falcosidekick metrics
  charts/falcosidekick/CHANGELOG.md
  charts/falcosidekick/Chart.yaml
  charts/falcosidekick/README.md
  charts/falcosidekick/dashboards/falcosidekick-grafana-dashboard.json
  charts/falcosidekick/templates/configmap-grafana-dashboard.yaml
  charts/falcosidekick/values.yaml
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/XXL, area/falcosidekick-chart

#803 add a grafana dashboard for the falco talon metrics
  charts/falco-talon/CHANGELOG.md
  charts/falco-talon/Chart.yaml
  charts/falco-talon/README.md
  charts/falco-talon/dashboards/falco-talon-grafana-dashboard.json
  charts/falco-talon/templates/configmap-grafana-dashboard.yaml
  charts/falco-talon/templates/configmap.yaml
  charts/falco-talon/values.yaml
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/XXL

#804 docs(.github): correct area labels
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation, dco-signoff: yes, size/XS, approved, lgtm

#808 remove non existing labels
  .github/dependabot.yml
Labels: dco-signoff: yes, size/XS, approved, lgtm, kind/cleanup
