Repository falcosecurity/charts, pull requests merged in 2024-10, with the labels that each got.

#737 Add possibility to add annotations to the metrics service
  charts/falco/CHANGELOG.md
  charts/falco/Chart.yaml
  charts/falco/README.md
  charts/falco/templates/service.yaml
  charts/falco/tests/unit/chartInfo.go
  charts/falco/tests/unit/serviceTemplate_test.go
  charts/falco/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/L

#757 fix(falcosidekick): customConfig mount path fix for webui redis
  charts/falcosidekick/CHANGELOG.md
  charts/falcosidekick/Chart.yaml
  charts/falcosidekick/templates/configmap-ui.yaml
  charts/falcosidekick/templates/deployment-ui.yaml
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, kind/chart-release, area/falcosidekick-chart

#758 update(falco): bump falco version to 0.39.1
  charts/falco/CHANGELOG.md
  charts/falco/Chart.yaml
  charts/falco/README.md
Labels: dco-signoff: yes, size/XS, approved, lgtm

#759 add falco-talon chart
  .github/PULL_REQUEST_TEMPLATE.md
  charts/falco-talon/CHANGELOG.md
  charts/falco-talon/Chart.yaml
  charts/falco-talon/README.gotmpl
  charts/falco-talon/README.md
  charts/falco-talon/rules.yaml
  charts/falco-talon/rules_override.yaml
  charts/falco-talon/templates/_helpers.tpl
  charts/falco-talon/templates/clusterrole.yaml
  charts/falco-talon/templates/configmap.yaml
  charts/falco-talon/templates/deployment.yaml
  charts/falco-talon/templates/ingress.yaml
  charts/falco-talon/templates/podsecuritypolicy.yaml
  charts/falco-talon/templates/rbac.yaml
  charts/falco-talon/templates/secrets.yaml
  charts/falco-talon/templates/servicemonitor.yaml
  charts/falco-talon/templates/services.yaml
  charts/falco-talon/values.yaml
Labels: dco-signoff: yes, approved, lgtm, kind/chart-release, size/XXL

#761 falco-talon: remove all refs to the previous org
  .lycheeignore
  charts/falco-talon/CHANGELOG.md
  charts/falco-talon/Chart.yaml
  charts/falco-talon/README.gotmpl
  charts/falco-talon/README.md
  charts/falco-talon/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/L, kind/cleanup

#766 chore(readme): add falco-talon chart link to readme
  README.md
Labels: dco-signoff: yes, size/XS, approved, lgtm

#767 fix: only prints env key if there are env values to be passed.
  charts/falco/CHANGELOG.md
  charts/falco/Chart.yaml
  charts/falco/README.md
  charts/falco/templates/_helpers.tpl
Labels: dco-signoff: yes, size/S, approved, lgtm
