Repository falcosecurity/charts, pull requests merged in 2025-01, with the labels that each got.

#773 chore(github): Generate release notes
  .github/workflows/release.yml
  cr.yaml
Labels: kind/documentation, dco-signoff: yes, size/XS, approved, lgtm, area/falco-chart

#779 fix(falcosidekick): Allow overriding the Prometheus scrape Service annotation
  charts/falcosidekick/CHANGELOG.md
  charts/falcosidekick/Chart.yaml
  charts/falcosidekick/README.md
  charts/falcosidekick/templates/service.yaml
  charts/falcosidekick/values.yaml
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, kind/chart-release, area/falcosidekick-chart

#822 fix(falco): bump version to 0.40.0
  charts/falco/CHANGELOG.md
  charts/falco/Chart.yaml
  charts/falco/README.md
Labels: dco-signoff: yes, size/S, approved, lgtm
